### PR TITLE
Add NLU unit tests

### PR DESCRIPTION
**Pull request by Mikemosca**
Add NLU unit tests.  Cover API and model setters/getters to increase
code coverage.

### CODE REVIEW

**Comment by Mikemosca** [comment]
see https://github.ibm.com/Watson/developer-experience/issues/2222 for code coverage numbers on these tests

Close #2222

**Comment by germanattanasio** [comment]
@Mikemosca I think the coverage is impacted because you are creating a pull request from a fork and we don't run the integration tests on forks.

**Comment by Mikemosca** [comment]
Oh, should I have used master?  My bad.  DO you need me to redo the pull request on master?

**Comment by germanattanasio** [comment]
No @Mikemosca, next time you should create a PR from a branch in this repo like I do. Initially I told you to use your fork but it was because you were learning about our workflow. No need for you to use a fork now

**Comment by Mikemosca** [comment]
@germanattanasio 
Cool, makes the process a bit easier

**Pull request merged**
