### PR TITLE
ci: Gha 9907

### PR DESCRIPTION
**Pull request by Mikemosca**
Add integration test workflow

### CODE REVIEW

**Review by kevinkowa — COMMENTED** [review]
is there an issue with these System.out.println ?

**Comment by Mikemosca** [comment]
> 



> is there an issue with these System.out.println ?

No.  I just commented them out because they add lots of output to the results stream.  I can put them back if they add value.  Up to you,

**Comment by kevinkowa** [comment]
> > 
> 
> > is there an issue with these System.out.println ?
> 
> No. I just commented them out because they add lots of output to the results stream. I can put them back if they add value. Up to you,

That's fine, just wondering

**Review by kevinkowa — APPROVED** [review]
lgtm!

**Pull request merged**
