### PR TITLE
Update Text to Speech customization interface

### PR DESCRIPTION
**Pull request by jeffpk62**
Update the Text to Speech customization interface to become more parallel with the service and with the Node SDK while maintaining the object-based approach to calling methods:

- Add `createCustomVoiceModel()` and `updateCustomVoiceModel()` methods, and deprecate `saveCustomVoiceModel()` method.  The new methods also prevent updating an existing model's language, and they make it possible to provide the capability to add words on an update.  This addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/531.

- Add `addWords()` and `addWord()` method, and deprecate `saveWords()` method.  This is purely to make the interface parallel with the service.  This addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/598.

- Add `getCustomVoiceModel()` method that accepts a model object instead of a customization ID.  The version that accepts an ID is preserved.  The new object-based signature brings the method in line with the other methods of the interface, which accept `CustomVoiceModel` objects to specify a model.

Miscellaneous improvements were also made to comments, JavaDoc, and parameter validation, and all tests and examples are updated accordingly.

### CODE REVIEW

**Comment by jeffpk62** [comment]
Not sure why test coverage percentage has dropped, since I actually added tests.  It could be that I removed tests for deprecated methods.  I could easily put those back if you prefer; they all still pass.

**Comment by germanattanasio** [comment]
Don't worry about test coverage now. The process is not stable enough yet.
I will take a look at this early next week jeff.

**Comment by jeffpk62** [comment]
@germanattanasio, I'll send you quick email summary of what to look at.  Most of this is straightforward and non-controversial, even trivial.  It's really the signatures of the create and update methods that you need to consider.  I'll briefly explain the motivation; they're easily reconsidered if you want changes.  Thanks.

**Comment by jeffpk62** [comment]
Add support for custom words to the `CustomVoiceModel` object by adding a list of `CustomTranslation` objects.  Also, rework the `updateCustomVoiceModel()` method to accept a single parameter, a model object, that can include updates to name and description and can also include one or more new custom word translations.  This PR addresses issue https://github.com/watson-developer-cloud/java-sdk/issues/533 and updates the previous commit for issue https://github.com/watson-developer-cloud/java-sdk/issues/531.  (@germanattanasio, this PR is now probably much more in line with your expectations.)

**Pull request merged**
