### PR TITLE
Added Timestamp / Word Confidence / Confidence Serialization/Deserialization to STT 

### PR DESCRIPTION
**Pull request by PranavSathy**
Added GSON serializer/deserializers for the timestamps, word_confidence & confidence attribute within the SpeechAlternative class. This needs to be integration tested, as my config.properties was empty and therefore had no ability to make API calls.

### CODE REVIEW

**Comment by daniel-bolanos** [comment]
Hello @PranavSathy , thank you for doing this, it is much appreciated. German will soon take a look at your pull request and process it. 

thanks again for your contribution, this makes a difference

Dani

**Comment by PranavSathy** [comment]
@daniel-bolanos @germanattanasio @jsstylos Any thoughts on the PR? Hope I am not catching you at a busy time

**Comment by germanattanasio** [comment]
@PranavSathy can you use [annotations](https://github.com/watson-developer-cloud/java-sdk/blob/master/src/main/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/model/column/Column.java#L25) and implement the serializer and deserializer as  [TypeAdapters](https://github.com/watson-developer-cloud/java-sdk/blob/master/src/main/java/com/ibm/watson/developer_cloud/tradeoff_analytics/v1/util/ColumnTypeAdapter.java). 

I've included an example from that we use for Columns in Tradeoff Analytics

**Comment by germanattanasio** [comment]
Let's do this, I will close this. make sure you get the latest changes from `dev` in your fork.
Next time you open the pull request write the name of the service at the beginning.

e.g:

```
[speech-to-text] Add support for Timestamp and Word Confidence
```

**Pull request closed without merging**
