### PR TITLE
[Tone Analyzer] Add content language parameter to Tone Analyzer

### PR DESCRIPTION
**Pull request by shubhanjan99**
### Summary

Add content language as a parameter to Tone Analyzer

### CODE REVIEW

**Comment by germanattanasio** [comment]
@shubhanjan99 can you update the PR? It has some conflicts

**Comment by shubhanjan99** [comment]
@germanattanasio I resolved the conflicts and updated here.

**Comment by germanattanasio** [comment]
@shubhanjan99 I'm working on a major release which will autogenerate the code for tone analyzer based on the swagger file. If you can take a look at #723 I would love to get your feedback.
This means that in the future you will only update the swagger and the SDKs will be autogenerated.

**Comment by germanattanasio** [comment]
Closing this in favor of #723

**Pull request closed without merging**
