### PR TITLE
Language Translation - Allow users to use a "Language" Enum instead of "String".

### LINKED ISSUE #225: Add constants for languages in Language Translation
The `LanguageTranslation` service API in the Java SDK does not define any constants for supported languages. For example, right now you have to write:

``` java
service.translate("hello", "en", "es");
```

Rather, having a set of pre-defined constants (an enum most likely) of languages supported by the service would be more helpful:

``` java
service.translate("hello", Language.EN, Language.ES);
```

### PR DESCRIPTION
**Pull request by tanmayb123**
Allow users to use an Enum, instead of Strings (i.e. "Language.ENGLISH" instead of  "en")
This should fix #225

### CODE REVIEW

**Comment by tanmayb123** [comment]
@GrapeBaBa Done. Thanks!

**Comment by GrapeBaBa** [comment]
@tanmayb123 That is not I mean. I paste the code, if/else always bad smell.

```
package com.ibm.watson.developer_cloud.language_translation.v2.model;

public enum Language {

    ARABIC {
        @Override
        public String toString() {
            return "ar";
        }
    }, ENGLISH {
        @Override
        public String toString() {
            return "en";
        }
    }, SPANISH {
        @Override
        public String toString() {
            return "es";
        }
    }, FRENCH {
        @Override
        public String toString() {
            return "fr";
        }
    }, ITALIAN {
        @Override
        public String toString() {
            return "it";
        }
    }, PORTUGUESE {
        @Override
        public String toString() {
            return "pt";
        }
    };

    @Override
    public String toString() {
        return "";
    }
}
```

**Comment by tanmayb123** [comment]
Thanks, done.

**Comment by tanmayb123** [comment]
Also, should we have things like "Language.ENGLISH" or "Language.EN"?

**Comment by germanattanasio** [comment]
Language.ENGLISH

Rule #1: NEVER EVER EVER use acronyms.
:P

**Comment by tanmayb123** [comment]
Got it!

**Comment by germanattanasio** [comment]
I'm merging the changes now

Thanks @tanmayb123

**Pull request merged**
