### PR TITLE
Adds serializedName for TranslatorModel

### LINKED ISSUE #684: [language-translator] Get model status return null
When I try the latest JDK, and use method getStatus() of com.ibm.watson.developer_cloud.language_translator.v2.model.TranslationModel, it always returns null. Please help to check. Thanks.

### PR DESCRIPTION
**Pull request by germanattanasio**
Fixes #684

### CODE REVIEW

**Comment by RollinJin** [comment]
Regarding the model status, there is another status "publishing", Please also include it in the TranslationModel. Thanks.

**Comment by germanattanasio** [comment]
Hey I don't see any "publishing" in the API Explorer: https://watson-api-explorer.mybluemix.net/apis/language-translator-v2#!/models/monitorTrainingModels

**Comment by RollinJin** [comment]
Hello, please double check with Watson language translator development
team, such as Andrzej Sakrajda/Watson/IBM, Jian-ming Xu/Watson/IBM. They
can confirm there is another status "publishing".  Thanks.

  |---------------+-----------------------------------------------------------------------------------------------------|
  |               |Rollin Jin 金源                                                                                      |
  |               |PMP® , Certified Big Data Architect                                                                  |
  |               |User Technologies, China Development Lab, IBM                                                        |
  |               |Tel +86 21 6092 2045; T/L:11902-22045                                                                |
  |               |jinyuan@cn.ibm.com                                                                                   |
  |               |Building 10, 399 Keyuan Road, Zhangjiang Hi-Tech Park, Pudong New District, Shanghai 201203,         |
  |               |P.R.CHINA                                                                                            |
  |               |上海浦东新区张江高科技园区科苑路399号10号楼(201203)                                                  |
  |---------------+-----------------------------------------------------------------------------------------------------|

**Comment by RollinJin** [comment]
screen shot 2017-05-12 at 9 52 28 am
Here comes some samples with publishing model status. Thanks.

**Pull request merged**
