### PR TITLE
Please verify, but seems Concept inherits from the wrong class

### PR DESCRIPTION
**Pull request by ruslan120101**

### CODE REVIEW

**Comment by ruslan120101** [comment]
Please keep me updated if the **Concept** class should indeed inherit from **AlchemyLanguageGenericModel**. I'll be accordingly updating the iOS SDK.

**Comment by ruslan120101** [comment]
@germanattanasio ? Please see comments above ^

**Comment by germanattanasio** [comment]
That's fixed already. I'll be pushing the changes later today

**Comment by germanattanasio** [comment]
Now that I'm looking I think concept should be inheriting from any class.

`EnrichedTitle` and `CombinedResults` are classes that use `Concept` and those are extending `AlchemyLanguageGenericModel` already

**Comment by germanattanasio** [comment]
The class should be:
```
public class Concept {
```

**Pull request merged**
