### PR TITLE
Use a proper format for the User-Agent

### PR DESCRIPTION
**Pull request by colindean**
Per an internal discussion, change the User-Agent to be in the valid format for a User-Agent.

### CODE REVIEW

**Comment by colindean** [comment]
I may be a little ahead of the game with the name change, @germanattanasio.

**Comment by germanattanasio** [comment]
what if we use `watson-apis` is that against the rules?

**Comment by colindean** [comment]
As in, `watson-apis-java-sdk/3.0.0-RC1`? That's valid.

**Comment by germanattanasio** [comment]
Yeah I would prefer that one.

**Comment by colindean** [comment]
Okay, I'll make that change tomorrow.

**Pull request merged**
