### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mediumTaj**
### Summary
This pull request removes duplicate table of contents from the readme.

### CODE REVIEW

**Review by kevinkowa — DISMISSED** [review]
LGTM!

**Review by SirSpidey — CHANGES_REQUESTED** [review]
Missing changes to `/discovery#usage`.

> Please note that the Discovery v2 API is accessible only on Cloud Pak for Data.

**Comment by mediumTaj** [comment]
Updated per allen's comment. @kevinkowa can you review again

**Review by SirSpidey — APPROVED** [review]
👍

**Review by kevinkowa — APPROVED** [review]
LGTM!

**Pull request merged**
