### PR TITLE
[text-to-speech] add functionality to get voice #287

### PR DESCRIPTION
**Pull request by ndrlslz**
### Summary

add getVoice(String voiceName) function

### CODE REVIEW

**Comment by germanattanasio** [comment]
This looks good. My only concern is that we are moving away from MockServer.
@max-vogler refactored the Text to Speech unit test so your pull request is not outdated.

**Comment by ndrlslz** [comment]
@germanattanasio, ok  i will switch tests to okhttp's MockWebServer.

**Comment by ndrlslz** [comment]
@germanattanasio, sorry, i don't know why others commits appear here. maybe the approach i merge code is worry. need i reopen a PR?

**Comment by germanattanasio** [comment]
mmm try with `git pull origin master` where `origin` is this github repository

**Comment by ndrlslz** [comment]
i don't konw how to deal with this, so i will create a new PR and close this.

**Pull request closed without merging**
